In [1]:
# Importing necessary libraries
import nfl_data_py as nfl
import pandas as pd

In [2]:
# Set display precision for readability
pd.set_option("display.precision", 1)
YEAR = [2024]
# Inital look of the season-level stats
nfl.import_seasonal_data(YEAR).head()

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0023459,2024,REG,368,584,3897.0,28,11.0,40.0,302.0,...,0.0e+00,0.0e+00,0.0e+00,0.0,0.0e+00,0.0e+00,0.0e+00,0.0e+00,0.0e+00,1.8e-01
1,00-0024243,2024,REG,0,0,0.0,0,0.0,0.0,0.0,...,6.8e-03,5.9e-02,8.8e-03,0.0,7.1e-02,5.6e-02,4.4e-03,7.1e-03,6.9e-02,1.1e-02
2,00-0026158,2024,REG,162,248,1761.0,12,7.0,18.0,123.0,...,0.0e+00,0.0e+00,0.0e+00,0.0,0.0e+00,0.0e+00,0.0e+00,0.0e+00,0.0e+00,1.6e-01
3,00-0026300,2024,REG,2,3,17.0,0,0.0,1.0,5.0,...,0.0e+00,0.0e+00,0.0e+00,0.0,0.0e+00,0.0e+00,0.0e+00,0.0e+00,0.0e+00,1.8e-03
4,00-0026498,2024,REG,340,517,3762.0,20,8.0,28.0,213.0,...,0.0e+00,0.0e+00,0.0e+00,0.0,0.0e+00,0.0e+00,0.0e+00,0.0e+00,0.0e+00,1.6e-01

In [3]:
# Pulling weekly stats for the 2024 season
weekly = nfl.import_weekly_data(YEAR)
print(weekly.head())

Downcasting floats.
    player_id player_name player_display_name position position_group  \
0  00-0023459   A.Rodgers       Aaron Rodgers       QB             QB
1  00-0023459   A.Rodgers       Aaron Rodgers       QB             QB
2  00-0023459   A.Rodgers       Aaron Rodgers       QB             QB
3  00-0023459   A.Rodgers       Aaron Rodgers       QB             QB
4  00-0023459   A.Rodgers       Aaron Rodgers       QB             QB

                                        headshot_url recent_team  season  \
0  https://static.www.nfl.com/image/upload/f_auto...         NYJ    2024
1  https://static.www.nfl.com/image/upload/f_auto...         NYJ    2024
2  https://static.www.nfl.com/image/upload/f_auto...         NYJ    2024
3  https://static.www.nfl.com/image/upload/f_auto...         NYJ    2024
4  https://static.www.nfl.com/image/upload/f_auto...         NYJ    2024

   week season_type  ... receiving_first_downs  receiving_epa  \
0     1         REG  ...                   0.0            NaN
1     2         REG  ...                   0.0            NaN
2     3         REG  ...                   0.0            NaN
3     4         REG  ...                   0.0            NaN
4     5         REG  ...                   0.0            NaN

   receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  \
0                          0   NaN           NaN              NaN   NaN
1                          0   NaN           NaN              NaN   NaN
2                          0   NaN           NaN              NaN   NaN
3                          0   NaN           NaN              NaN   NaN
4                          0   NaN           NaN              NaN   NaN

   special_teams_tds  fantasy_points  fantasy_points_ppr
0                0.0             8.6                 8.6
1                0.0            15.1                15.1
2                0.0            21.0                21.0
3                0.0            11.6                11.6
4                0.0            11.8                11.8

[5 rows x 53 columns]

In [4]:
# Rows and Columns
print(weekly.shape)

(5597, 53)

In [5]:
# List of every Column
print(weekly.columns)

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [6]:
# Every unique player name
print(weekly["player_display_name"].unique())

['Aaron Rodgers' 'Marcedes Lewis' 'Joe Flacco' 'Josh Johnson'
 'Matthew Stafford' 'Andy Dalton' 'Tyrod Taylor' 'Johnny Hekker'
 'Rodney McLeod' 'Russell Wilson' 'Kirk Cousins' 'Bryan Anger'
 'Kyle Juszczyk' 'Adam Thielen' 'Zach Ertz' 'Tress Way' 'Keenan Allen'
 'Robert Woods' 'Travis Kelce' 'DeAndre Hopkins' 'Geno Smith'
 'Cordarrelle Patterson' 'Odell Beckham' 'Brandin Cooks'
 'Teddy Bridgewater' 'Derek Carr' 'Jordan Matthews' 'Jimmy Garoppolo'
 'C.J. Goodwin' 'Davante Adams' 'Mike Evans' 'Allen Robinson'
 'Chris Manhertz' 'Jameis Winston' 'Amari Cooper' 'Nelson Agholor'
 'MyCole Pruitt' 'Stefon Diggs' 'Michael Burton' 'Raheem Mostert'
 'Eric Tomlinson' 'DeAndre Carter' 'Taylor Heinicke' 'Jamison Crowder'
 'Ameer Abdullah' 'Chris Conley' 'Geoff Swaim' 'Tyler Lockett'
 'Marcus Mariota' 'Taylor Decker' 'Sterling Shepard' 'Austin Hooper'
 'Nick Vannett' 'Miles Killebrew' 'Brandon Allen' 'Kalif Raymond'
 'Robbie Chosen' 'Derrick Henry' 'Demarcus Robinson' 'C.J. Ham'
 'Riley Dixon' 'Carson Wentz' 'Tyler Boyd' 'Tyreek Hill' 'Ezekiel Elliott'
 'Dak Prescott' 'Hunter Henry' 'Jared Goff' 'Tyler Higbee'
 'Jacoby Brissett' 'Mo Alie-Cox' 'Johnny Mundt' 'Christian McCaffrey'
 'Curtis Samuel' 'George Kittle' 'Trent Taylor' 'Aaron Jones'
 'Kendrick Bourne' 'Nick Mullens' 'Taysom Hill' 'Tim Patrick'
 'Patrick Ricard' 'Pharaoh Brown' 'John Ross' 'Samaje Perine'
 'Mike Williams' 'Deshaun Watson' 'James Conner' 'Mack Hollins'
 'Jalen Reeves-Maybin' 'Eric Saubert' 'David Moore' 'Noah Brown'
 'Cooper Rush' 'Austin Ekeler' 'Dare Ogunbowale' 'JuJu Smith-Schuster'
 'Jonnu Smith' 'Dan Skipper' 'Mitchell Trubisky' 'Patrick Mahomes'
 'Evan Engram' 'David Njoku' 'Zay Jones' 'Dalvin Cook' 'Gerald Everett'
 'Joe Mixon' 'Alvin Kamara' 'Cooper Kupp' 'Chris Godwin' 'Kareem Hunt'
 "D'Onta Foreman" 'Josh Reynolds' 'Jamaal Williams' 'Joshua Dobbs'
 'Jeremy McNichols' 'River Cracraft' 'Ross Dwelley' 'Jeffery Wilson'
 'Will Dissly' 'J.K. Scott' 'Tim Boyle' 'Gus Edwards' 'Mike Boone'
 'Tyler Conklin' 'Marquez Valdes-Scantling' 'Courtland Sutton'
 'Dallas Goedert' 'Anthony Miller' 'Jordan Akins' 'Ian Thomas'
 'Dalton Schultz' 'Justin Watson' 'Mike White' 'Ray-Ray McCloud'
 'Cedrick Wilson' 'Braxton Berrios' 'Jonathan Owens' 'Trent Sherfield'
 'Tavierre Thomas' 'Allen Lazard' 'Trenton Scott' 'Kyle Allen'
 'Tanner Hudson' 'Brandon Powell' 'Mark Andrews' 'Mason Rudolph'
 'Christian Kirk' 'D.J. Chark' 'Nick Chubb' 'Lamar Jackson'
 'Durham Smythe' 'D.J. Moore' 'Mike Gesicki' 'Hayden Hurst' 'Sam Hubbard'
 'Calvin Ridley' 'Saquon Barkley' 'KhaDarel Hodge' 'Baker Mayfield'
 'Josh Allen' 'Dante Pettis' 'Sam Darnold' 'Steven Sims' 'Andrew Beck'
 'Jakobi Meyers' 'Irv Smith' 'Alexander Mattison' 'Julian Love'
 'Justice Hill' 'Foster Moreau' 'Ashton Dulin' 'Jake Browning'
 'Alec Ingold' 'Mecole Hardman' 'Jack Fox' 'A.J. Cole' 'Olamide Zaccheaus'
 'Diontae Johnson' 'Kyler Murray' 'T.J. Hockenson' 'Miles Sanders'
 'Josh Oliver' 'Devin Singletary' 'Tony Pollard' 'Jarrett Stidham'
 'Jake Bailey' 'Gardner Minshew' 'Scott Miller' 'Myles Gaskin'
 'Trenton Irwin' "Lil'Jordan Humphrey" 'Greg Dortch' 'Darius Slayton'
 'Ty Johnson' 'Tom Kennedy' 'Joseph Fortson' 'Craig Reynolds'
 'Travis Homer' 'Alex Bachman' "D'Ernest Johnson" 'Drew Sample'
 'Parris Campbell' 'DK Metcalf' 'Noah Fant' 'Terry McLaurin'
 'Marquise Brown' 'A.J. Brown' 'David Montgomery' 'Dawson Knox'
 'Josh Jacobs' 'Drew Lock' 'Daniel Jones' 'Deebo Samuel' 'James Pierre'
 'Jamycal Hasty' 'Tony Jones' 'Cody White' 'Jonathan Ward'
 'Patrick Taylor' 'Dan Chisena' 'Tyler Huntley' 'Sam Franklin'
 'Juwan Johnson' 'J.J. Taylor' 'James Proche' 'Rico Dowdle' 'J.K. Dobbins'
 'Isaiah Hodgins' 'Mason Kinsey' 'Nick Westbrook-Ikhine'
 'Kristian Wilkerson' 'Reggie Gilliam' 'Gabe Davis' 'Tua Tagovailoa'
 'Jonathan Taylor' 'Harrison Bryant' 'Colby Parkinson' 'Zack Moss'
 'Michael Pittman' 'Collin Johnson' 'Jauan Jennings' 'Brandon Aiyuk'
 'Jordan Love' 'Laviska Shenault Jr.' "D'Andre Swift" 'Cole Kmet'
 'Darrynton Evans' 'Darnell Mooney' 'Justin Jefferson' 'Antonio Gibson'
 'Ashtyn Davis' 'Devin Duvernay' 'Josiah Deguara' 'K.J. Osborn'
 'Justin Herbert' 'CeeDee Lamb' 'Clyde Edwards-Helaire' 'Joshua Kelley'
 'Jalen Reagor' 'Jalen Hurts' 'Jerry Jeudy' 'Tee Higgins' 'Cam Akers'
 'Van Jefferson' 'Adam Trautman' 'DeeJay Dallas' 'Tyler Johnson'
 'Charlie Woerner' 'Stephen Sullivan' 'Joe Burrow' "Ke'Shawn Vaughn"
 'Chris Blair' 'Tim Jones' 'Kenny Yeboah' 'D.J. Turner' 'Shane Zylstra'
 'Rashod Bateman' 'Nico Collins' 'Chuba Hubbard' 'Brevin Jordan'
 'Deommodore Lenoir' 'Quintin Morris' 'Jaylen Waddle' "D'Wayne Eskridge"
 'Dyami Brown' 'John Bates' 'Tylan Wallace' 'Ihmir Smith-Marsette'
 'Noah Gray' 'Zach Davidson' 'Simi Fehoko' 'Jermar Jefferson'
 'Adam Prentice' 'Jack Stoll' 'Brock Wright' 'Feleipe Franks'
 'Austin Trammell' 'Kene Nwangwu' 'Tutu Atwell' 'Ben Skowronek'
 'Rhamondre Stevenson' 'Kylen Granson' 'Jaelon Darden' 'Penei Sewell'
 'Luke Farrell' 'Najee Harris' 'Pat Freiermuth' 'Davis Mills'
 "Ja'Marr Chase" 'Khalil Herbert' 'DeVonta Smith' 'Kadarius Toney'
 'Kenneth Gainwell' 'Michael Carter' 'Kyle Trask' 'Justin Fields'
 'Terrace Marshall' 'Amon-Ra St. Brown' 'Kyle Pitts' 'Trevor Lawrence'
 'Mac Jones' 'Travis Etienne' 'Elijah Moore' 'Trey Sermon' 'Josh Palmer'
 'Divine Deablo' 'Javonte Williams' 'Hunter Long' 'Tommy Tremble'
 'Trey Lance' 'Sam Howell' 'Tyler Badie' 'Grant Calcaterra' 'Bo Melton'
 'Dareke Young' 'Tyler Goodson' 'Josh Blackwell' 'Britain Covey'
 'Irvin Charles' 'Isiah Pacheco' 'Mike Caliendo' 'Justyn Ross'
 'Jaylen Warren' 'Kevin Austin' 'Drake London' 'Chris Olave'
 'Jameson Williams' 'Tyler Smith' 'George Pickens' 'James Cook'
 'Greg Dulcich' 'Marcus Jones' 'Rachaad White' 'David Bell'
 'Dameon Pierce' 'Khalil Shakir' 'Tyler Allgeier' 'Jerome Ford'
 'Ty Chandler' 'Matt Araiza' 'Vederian Lowe' 'Jalen Nailor'
 'Andrew Ogletree' 'Mike Woods' 'Connor Heyward' 'John FitzPatrick'
 'Chris Oladokun' 'Skylar Thompson' 'Tanner Conner' 'Brandon Johnson'
 'Kendric Pryor' 'Raheem Blackshear' 'Tyreik McAllister' 'Stone Smartt'
 'Deven Thompkins' 'J.J. Russell' 'Sincere McCormick' 'Tay Martin'
 'Jordan Mason' 'Lucas Krull' 'Rashid Shaheed' 'Ronnie Rivers'
 'Peyton Hendershot' 'Juanyeh Thomas' 'Julius Chestnut' 'Aaron Shampklin'
 'John Metchie' 'Hassan Haskins' 'Tucker Fisk' 'Alec Pierce'
 'Jalen Tolbert' 'Garrett Wilson' 'Jahan Dotson' 'Treylon Burks'
 'Trey McBride' 'Velus Jones' 'Brian Robinson' 'Kavontae Turpin'
 'Jeremy Ruckert' 'Chigoziem Okonkwo' 'Romeo Doubs' 'Tyrion Davis-Price'
 'Brock Purdy' 'Calvin Austin' 'Isaiah Likely' 'Kyren Williams'
 'Zamir White' 'Jake Ferguson' 'Charlie Kolar' 'Skyy Moore'
 'Erik Ezukanma' 'Pierre Strong' 'Kenny Pickett' 'Tyquan Thornton'
 'Bailey Zappe' 'Daniel Bellinger' "Wan'Dale Robinson" 'Breece Hall'
 'Desmond Ridder' 'Dane Belton' 'Christian Watson' 'Malik Willis'
 'Cade Otton' 'Kenneth Walker' 'Xavier Smith' 'Dontayvion Wicks'
 'Will Mallory' 'Eric Gray' 'Tanner McKee' 'Tyson Bagent'
 'Keaton Mitchell' 'Malik Heath' 'Tommy DeVito' 'Bryce Ford-Wheaton'
 'Ben VanSumeren' 'Xavier Gipson' 'E.J. Jenkins' 'Grant DuBose'
 'Nikko Remigio' 'Bijan Robinson' 'Jaxon Smith-Njigba' 'Quentin Johnston'
 'Luke Schoonmaker' 'Hendon Hooker' 'Kendre Miller' 'Tank Bigsby'
 'Darnell Washington' 'Michael Wilson' 'Tre Tucker' 'Derius Davis'
 'Charlie Jones' "Aidan O'Connell" 'Clayton Tune'
 'Dorian Thompson-Robinson' 'Josh Whyle' 'Chase Brown' 'Parker Washington'
 'Kayshon Boutte' 'Chris Rodriguez' 'Scott Matlock' 'Xavier Hutchinson'
 'Andrei Iosivas' 'Demario Douglas' 'Deuce Vaughn' 'Kenny McIntosh'
 'Jalen Brooks' 'Brayden Willis' 'Ronnie Bell' 'Jordan Mims'
 'Tyrell Shavers' 'Christopher Brooks' 'Emari Demercado'
 'Blake Whiteheart' 'Julian Hill' 'Jared Wayne' 'Hunter Luepke'
 'Jake Bobo' 'Nate Adkins' 'Jaleel McLaughlin' 'Emanuel Wilson' 'Ben Sims'
 'Rakim Jarrett' 'Ryan Miller' 'Brycen Tremayne' 'John Samuel Shenker'
 'Dalton Kincaid' 'Brenton Strange' 'Jalin Hyatt' 'Tyler Scott'
 'Sean Tucker' 'Marvin Mims' 'Tank Dell' 'Cedric Tillman' 'Wanya Morris'
 'Jordan Addison' 'Tucker Kraft' 'Josh Downs' 'Jake Haener'
 'Roschon Johnson' 'Tyjae Spears' 'Devon Achane' 'Elijah Higgins'
 'Payne Durham' 'Trey Palmer' 'Jonathan Mingo' 'Zay Flowers' 'Sam LaPorta'
 'Michael Mayer' 'Rashee Rice' 'Davis Allen' 'Puka Nacua' 'Jahmyr Gibbs'
 'Luke Musgrave' 'Jayden Reed' 'Bryce Young' 'Will Levis' 'C.J. Stroud'
 'Anthony Richardson' 'Zach Charbonnet' 'Johnny Wilson' 'Chris Collier'
 'George Holani' 'Baylor Cupp' 'Carson Steele' 'Malik Nabers'
 'Brock Bowers' 'Xavier Legette' 'Jonathon Brooks' 'Luke McCaffrey'
 "Ja'Tavion Sanders" 'Cade Stover' 'Bucky Irving' 'Isaac Guerendo'
 'Sione Vaki' 'Jacob Cowing' 'Audric Estime' 'Spencer Rattler'
 'Jamari Thrash' 'Tyrone Tracy' 'Bub Means' 'Kimani Vidal'
 "Jha'Quan Jackson" 'Jase McClellan' 'Casey Washington' 'Joe Milton'
 'Dylan Laube' 'Ryan Flournoy' 'Jaheim Bell' 'Devaughn Vele'
 'Isaiah Williams' 'Brenden Bates' 'Jalen Coker' 'Xavier Weaver'
 'Brevyn Spann-Ford' 'Ramel Keyton' 'Blake Watson' 'Kameron Johnson'
 'British Brooks' 'Matthew Hayball' 'Dallin Holker' 'Jermaine Jackson'
 'Jacob Kibodi' 'Mason Tipton' 'Cam Grandy' 'David Martin-Robinson'
 'Bryce Oliver' 'Dell Pettus' 'Cody Schrader' 'J.C. Latham' 'Bo Nix'
 'Tip Reiman' 'Blake Corum' 'Will Shipley' 'Ainias Smith'
 'Jordan Whittington' 'Devin Culp' 'Terrell Jennings' 'Devontez Walker'
 'A.J. Barner' 'Braelon Allen' 'Rasheen Ali' 'Isaiah Davis'
 'Jermaine Burton' 'MarShawn Lloyd' 'Erick All' 'Anthony Gould'
 'Jared Wiley' 'Jaden Hicks' 'Theo Johnson' 'Marvin Harrison' 'Drake Maye'
 'Javon Baker' 'Jalen McMillan' 'Troy Franklin' 'Jaylen Wright'
 'Ray Davis' 'Malik Washington' 'Adonai Mitchell' 'Brian Thomas'
 'Xavier Worthy' 'Keon Coleman' "Ja'Lynn Polk" 'Jayden Daniels'
 'Ben Sinnott' 'Ladd McConkey' 'Ricky Pearsall' 'Michael Penix'
 'Caleb Williams' 'Rome Odunze' 'Malachi Corley' 'Trey Benson']

In [7]:
# Number of distinct players
print(weekly["player_display_name"].unique().shape)

(612,)

In [8]:
# Position labels
print(weekly["position"].unique())

['QB' 'TE' 'P' 'FS' 'FB' 'WR' 'RB' 'CB' 'T' 'SS' 'OLB' 'DE' 'MLB' 'G'
 'ILB']

In [9]:
# Position groups
print(weekly["position_group"].unique())

['QB' 'TE' 'SPEC' 'DB' 'RB' 'WR' 'OL' 'LB' 'DL']

In [10]:
# Count rows per position
print(weekly['position'].value_counts())

WR     2238
RB     1408
TE     1137
QB      697
FB       72
P        14
CB        7
T         7
SS        7
FS        4
G         2
OLB       1
DE        1
MLB       1
ILB       1
Name: position, dtype: int64

In [11]:
# Narrow down to only the columns we actually need going forward, drop the rest
weekly = weekly[["player_display_name",
"position",
"recent_team",
"season_type",
"fantasy_points_ppr"]]

print(weekly)

     player_display_name position recent_team season_type  fantasy_points_ppr
0          Aaron Rodgers       QB         NYJ         REG                 8.6
1          Aaron Rodgers       QB         NYJ         REG                15.1
2          Aaron Rodgers       QB         NYJ         REG                21.0
3          Aaron Rodgers       QB         NYJ         REG                11.6
4          Aaron Rodgers       QB         NYJ         REG                11.8
...                  ...      ...         ...         ...                 ...
5592         Trey Benson       RB         ARI         REG                10.7
5593         Trey Benson       RB         ARI         REG                 1.8
5594         Trey Benson       RB         ARI         REG                 2.0
5595         Trey Benson       RB         ARI         REG                 2.9
5596         Trey Benson       RB         ARI         REG                 2.2

[5597 rows x 5 columns]

In [12]:
# Season types
print(weekly["season_type"].unique())

['REG' 'POST']

In [13]:
# Drop playoff stats and keep regual season stats
weekly = weekly[weekly["season_type"] == "REG"]
print(weekly)

     player_display_name position recent_team season_type  fantasy_points_ppr
0          Aaron Rodgers       QB         NYJ         REG                 8.6
1          Aaron Rodgers       QB         NYJ         REG                15.1
2          Aaron Rodgers       QB         NYJ         REG                21.0
3          Aaron Rodgers       QB         NYJ         REG                11.6
4          Aaron Rodgers       QB         NYJ         REG                11.8
...                  ...      ...         ...         ...                 ...
5592         Trey Benson       RB         ARI         REG                10.7
5593         Trey Benson       RB         ARI         REG                 1.8
5594         Trey Benson       RB         ARI         REG                 2.0
5595         Trey Benson       RB         ARI         REG                 2.9
5596         Trey Benson       RB         ARI         REG                 2.2

[5340 rows x 5 columns]

In [14]:
# Keep only the four offensive skill positions
keep_positions = ["WR", "RB", "TE", "QB"]
weekly = weekly[weekly["position"].isin(keep_positions)]
print(weekly)

     player_display_name position recent_team season_type  fantasy_points_ppr
0          Aaron Rodgers       QB         NYJ         REG                 8.6
1          Aaron Rodgers       QB         NYJ         REG                15.1
2          Aaron Rodgers       QB         NYJ         REG                21.0
3          Aaron Rodgers       QB         NYJ         REG                11.6
4          Aaron Rodgers       QB         NYJ         REG                11.8
...                  ...      ...         ...         ...                 ...
5592         Trey Benson       RB         ARI         REG                10.7
5593         Trey Benson       RB         ARI         REG                 1.8
5594         Trey Benson       RB         ARI         REG                 2.0
5595         Trey Benson       RB         ARI         REG                 2.9
5596         Trey Benson       RB         ARI         REG                 2.2

[5227 rows x 5 columns]

In [15]:
# Sum each player's weekly points into a season total, sorted highest to lowest
weekly = weekly.groupby(
    ["player_display_name", "position", "recent_team"],
    as_index=False
)["fantasy_points_ppr"].sum()
weekly = weekly.sort_values(by="fantasy_points_ppr", ascending=False)
weekly = weekly.reset_index(drop=True)
print(weekly)

    player_display_name position recent_team  fantasy_points_ppr
0         Lamar Jackson       QB         BAL               430.4
1         Ja'Marr Chase       WR         CIN               403.0
2            Joe Burrow       QB         CIN               372.8
3            Josh Allen       QB         BUF               372.3
4        Baker Mayfield       QB          TB               365.8
..                  ...      ...         ...                 ...
567        Tyson Bagent       QB         CHI                -0.3
568      Kadarius Toney       WR         CLE                -0.4
569          Sam Howell       QB         SEA                -0.8
570         Dylan Laube       RB          LV                -2.0
571        Clayton Tune       QB         ARI                -2.1

[572 rows x 4 columns]

In [16]:
# Check for players appearing more than once -- flags players traded mid-season
name_counts = weekly['player_display_name'].value_counts()
name_counts[name_counts > 1]

Diontae Johnson             3
Velus Jones                 2
Josh Reynolds               2
Marquez Valdes-Scantling    2
Jonathan Mingo              2
Mike Williams               2
Cam Akers                   2
Davante Adams               2
DeAndre Hopkins             2
Tim Boyle                   2
Amari Cooper                2
Khalil Herbert              2
Name: player_display_name, dtype: int64

In [17]:
# Fix the trade-splitting problem
# Sum points by name + position only
points_totals = weekly.groupby(
    ['player_display_name', 'position'],
    as_index=False
)['fantasy_points_ppr'].sum()
# Compute each player's most-played team
primary_team = (
    weekly.groupby(['player_display_name', 'recent_team'])
    .size()
    .reset_index(name='weeks_with_team')
    .sort_values('weeks_with_team', ascending=False)
    .drop_duplicates(subset='player_display_name', keep='first')
    [['player_display_name', 'recent_team']]
)
# Merge the two together
final = points_totals.merge(primary_team, on='player_display_name', how='left')
final = final.sort_values('fantasy_points_ppr', ascending=False).reset_index(drop=True)
final

    player_display_name position  fantasy_points_ppr recent_team
0         Lamar Jackson       QB               430.4         BAL
1         Ja'Marr Chase       WR               403.0         CIN
2            Joe Burrow       QB               372.8         CIN
3            Josh Allen       QB               372.3         BUF
4        Baker Mayfield       QB               365.8          TB
..                  ...      ...                 ...         ...
554        Tyson Bagent       QB                -0.3         CHI
555      Kadarius Toney       WR                -0.4         CLE
556          Sam Howell       QB                -0.8         SEA
557         Dylan Laube       RB                -2.0          LV
558        Clayton Tune       QB                -2.1         ARI

[559 rows x 4 columns]

In [18]:
#Check for duplicates
final['player_display_name'].value_counts().loc[lambda x: x > 1]

Series([], Name: player_display_name, dtype: int64)

In [19]:
# Original weekly data
raw = nfl.import_weekly_data(YEAR)
raw = raw[raw["season_type"] == "REG"]
raw = raw[raw["position"].isin(["WR", "RB", "TE", "QB"])]
# Count how many distinct weeks each player played
games_played = (
    raw.groupby("player_display_name")["week"]
    .nunique()
    .reset_index(name="games_played")
)
games_played.head()

Downcasting floats.

  player_display_name  games_played
0         A.J. Barner            14
1          A.J. Brown            13
2         Aaron Jones            17
3       Aaron Rodgers            17
4     Aaron Shampklin             3

In [20]:
# Attach the games_played count onto each player's row in `final`
final = final.merge(games_played, on="player_display_name", how="left")
final

    player_display_name position  fantasy_points_ppr recent_team  games_played
0         Lamar Jackson       QB               430.4         BAL            17
1         Ja'Marr Chase       WR               403.0         CIN            17
2            Joe Burrow       QB               372.8         CIN            17
3            Josh Allen       QB               372.3         BUF            16
4        Baker Mayfield       QB               365.8          TB            17
..                  ...      ...                 ...         ...           ...
554        Tyson Bagent       QB                -0.3         CHI             4
555      Kadarius Toney       WR                -0.4         CLE             2
556          Sam Howell       QB                -0.8         SEA             1
557         Dylan Laube       RB                -2.0          LV             1
558        Clayton Tune       QB                -2.1         ARI             5

[559 rows x 5 columns]

In [21]:
# Look at the distribution of games_played to decide where to draw the minimum-games cutoff
final["games_played"].describe()
final["games_played"].value_counts().sort_index()

1     60
2     42
3     29
4     29
5     23
6     18
7     29
8     23
9     14
10    28
11    26
12    22
13    32
14    35
15    44
16    37
17    68
Name: games_played, dtype: int64

In [22]:
# Drop anyone who played fewer than 4 games (filters out small-sample noise)
final = final[final["games_played"] >= 4].reset_index(drop=True)
final.shape

(428, 5)

In [23]:
# Confirm how many players remain at each position after filtering
final["position"].value_counts()

WR    172
RB    105
TE     93
QB     58
Name: position, dtype: int64

In [24]:
# Build a team x position grid to check whether every team still has depth at every position
team_position_counts = final.groupby(["recent_team", "position"]).size().unstack(fill_value=0)
team_position_counts[(team_position_counts == 0).any(axis=1)]
team_position_counts

position     QB  RB  TE  WR
recent_team
ARI           2   4   3   4
ATL           2   2   2   4
BAL           2   3   3   5
BUF           2   3   3   5
CAR           2   3   2   6
CHI           2   3   2   4
CIN           1   3   5   5
CLE           3   4   3   6
DAL           3   3   3   6
DEN           1   3   3   6
DET           1   4   2   5
GB            2   3   3   6
HOU           2   4   2   6
IND           2   3   4   5
JAX           2   3   3   5
KC            1   4   3   5
LA            1   3   3   6
LAC           2   4   5   7
LV            3   4   3   5
MIA           2   4   3   5
MIN           2   2   3   5
NE            2   3   2   7
NO            3   4   3   7
NYG           2   3   3   4
NYJ           1   3   3   5
PHI           2   3   2   5
PIT           2   3   4   5
SEA           1   3   3   5
SF            1   4   2   5
TB            1   3   2   7
TEN           2   3   3   5
WAS           1   4   3   6

In [25]:
# Check final's column names so we can hardcode D/ST and K data below to match the same shape
final.columns.tolist()

['player_display_name',
 'position',
 'fantasy_points_ppr',
 'recent_team',
 'games_played']

In [26]:
# Hardcoding the 32 teams defenses from 2024 season (D/ST)
# FantasyPros helped fill that gap since nfl_data_py library doesn't have defense stats
dst_data = pd.DataFrame([
    {"player_display_name": "Denver Broncos D/ST",        "position": "DST", "recent_team": "DEN", "fantasy_points_ppr": 179.0, "games_played": 17},
    {"player_display_name": "Minnesota Vikings D/ST",      "position": "DST", "recent_team": "MIN", "fantasy_points_ppr": 162.0, "games_played": 17},
    {"player_display_name": "Green Bay Packers D/ST",      "position": "DST", "recent_team": "GB",  "fantasy_points_ppr": 148.0, "games_played": 17},
    {"player_display_name": "Pittsburgh Steelers D/ST",    "position": "DST", "recent_team": "PIT", "fantasy_points_ppr": 146.0, "games_played": 17},
    {"player_display_name": "Houston Texans D/ST",         "position": "DST", "recent_team": "HOU", "fantasy_points_ppr": 139.0, "games_played": 17},
    {"player_display_name": "Seattle Seahawks D/ST",       "position": "DST", "recent_team": "SEA", "fantasy_points_ppr": 136.0, "games_played": 17},
    {"player_display_name": "Philadelphia Eagles D/ST",    "position": "DST", "recent_team": "PHI", "fantasy_points_ppr": 135.0, "games_played": 17},
    {"player_display_name": "Buffalo Bills D/ST",          "position": "DST", "recent_team": "BUF", "fantasy_points_ppr": 133.0, "games_played": 17},
    {"player_display_name": "Los Angeles Chargers D/ST",   "position": "DST", "recent_team": "LAC", "fantasy_points_ppr": 128.0, "games_played": 17},
    {"player_display_name": "Detroit Lions D/ST",          "position": "DST", "recent_team": "DET", "fantasy_points_ppr": 123.0, "games_played": 17},
    {"player_display_name": "Chicago Bears D/ST",          "position": "DST", "recent_team": "CHI", "fantasy_points_ppr": 121.0, "games_played": 17},
    {"player_display_name": "Baltimore Ravens D/ST",       "position": "DST", "recent_team": "BAL", "fantasy_points_ppr": 120.0, "games_played": 17},
    {"player_display_name": "Los Angeles Rams D/ST",       "position": "DST", "recent_team": "LA", "fantasy_points_ppr": 118.0, "games_played": 17},
    {"player_display_name": "Dallas Cowboys D/ST",         "position": "DST", "recent_team": "DAL", "fantasy_points_ppr": 111.0, "games_played": 17},
    {"player_display_name": "Kansas City Chiefs D/ST",     "position": "DST", "recent_team": "KC",  "fantasy_points_ppr": 106.0, "games_played": 17},
    {"player_display_name": "Cincinnati Bengals D/ST",     "position": "DST", "recent_team": "CIN", "fantasy_points_ppr": 104.0, "games_played": 17},
    {"player_display_name": "Tampa Bay Buccaneers D/ST",   "position": "DST", "recent_team": "TB",  "fantasy_points_ppr": 104.0, "games_played": 17},
    {"player_display_name": "Arizona Cardinals D/ST",      "position": "DST", "recent_team": "ARI", "fantasy_points_ppr": 101.0, "games_played": 17},
    {"player_display_name": "New Orleans Saints D/ST",     "position": "DST", "recent_team": "NO",  "fantasy_points_ppr": 98.0,  "games_played": 17},
    {"player_display_name": "Atlanta Falcons D/ST",        "position": "DST", "recent_team": "ATL", "fantasy_points_ppr": 97.0,  "games_played": 17},
    {"player_display_name": "New York Jets D/ST",          "position": "DST", "recent_team": "NYJ", "fantasy_points_ppr": 95.0,  "games_played": 17},
    {"player_display_name": "New York Giants D/ST",        "position": "DST", "recent_team": "NYG", "fantasy_points_ppr": 91.0,  "games_played": 17},
    {"player_display_name": "Indianapolis Colts D/ST",     "position": "DST", "recent_team": "IND", "fantasy_points_ppr": 91.0,  "games_played": 17},
    {"player_display_name": "Washington Commanders D/ST",  "position": "DST", "recent_team": "WAS", "fantasy_points_ppr": 90.0,  "games_played": 17},
    {"player_display_name": "Miami Dolphins D/ST",         "position": "DST", "recent_team": "MIA", "fantasy_points_ppr": 84.0,  "games_played": 17},
    {"player_display_name": "San Francisco 49ers D/ST",    "position": "DST", "recent_team": "SF",  "fantasy_points_ppr": 84.0,  "games_played": 17},
    {"player_display_name": "Cleveland Browns D/ST",       "position": "DST", "recent_team": "CLE", "fantasy_points_ppr": 81.0,  "games_played": 17},
    {"player_display_name": "Tennessee Titans D/ST",       "position": "DST", "recent_team": "TEN", "fantasy_points_ppr": 72.0,  "games_played": 17},
    {"player_display_name": "Las Vegas Raiders D/ST",      "position": "DST", "recent_team": "LV",  "fantasy_points_ppr": 71.0,  "games_played": 17},
    {"player_display_name": "Jacksonville Jaguars D/ST",   "position": "DST", "recent_team": "JAX", "fantasy_points_ppr": 71.0,  "games_played": 17},
    {"player_display_name": "New England Patriots D/ST",   "position": "DST", "recent_team": "NE",  "fantasy_points_ppr": 63.0,  "games_played": 17},
    {"player_display_name": "Carolina Panthers D/ST",      "position": "DST", "recent_team": "CAR", "fantasy_points_ppr": 41.0,  "games_played": 17},
])

In [27]:
# Hardcoding the 2024 season kickers who played 4+ games
# FantasyPros helped fill that gap since nfl_data_py library doesn't have kicker stats
k_data = pd.DataFrame([
    {"player_display_name": "Brandon Aubrey",     "position": "K", "recent_team": "DAL", "fantasy_points_ppr": 192.0, "games_played": 17},
    {"player_display_name": "Chris Boswell",      "position": "K", "recent_team": "PIT", "fantasy_points_ppr": 191.0, "games_played": 17},
    {"player_display_name": "Cameron Dicker",     "position": "K", "recent_team": "LAC", "fantasy_points_ppr": 179.0, "games_played": 17},
    {"player_display_name": "Ka'imi Fairbairn",   "position": "K", "recent_team": "HOU", "fantasy_points_ppr": 172.0, "games_played": 17},
    {"player_display_name": "Jason Sanders",      "position": "K", "recent_team": "MIA", "fantasy_points_ppr": 166.0, "games_played": 17},
    {"player_display_name": "Chase McLaughlin",   "position": "K", "recent_team": "TB",  "fantasy_points_ppr": 164.0, "games_played": 17},
    {"player_display_name": "Jake Bates",         "position": "K", "recent_team": "DET", "fantasy_points_ppr": 161.0, "games_played": 17},
    {"player_display_name": "Wil Lutz",           "position": "K", "recent_team": "DEN", "fantasy_points_ppr": 160.0, "games_played": 17},
    {"player_display_name": "Tyler Bass",         "position": "K", "recent_team": "BUF", "fantasy_points_ppr": 146.0, "games_played": 17},
    {"player_display_name": "Daniel Carlson",     "position": "K", "recent_team": "LV",  "fantasy_points_ppr": 145.0, "games_played": 17},
    {"player_display_name": "Justin Tucker",      "position": "K", "recent_team": "BAL", "fantasy_points_ppr": 143.0, "games_played": 17},
    {"player_display_name": "Jake Elliott",       "position": "K", "recent_team": "PHI", "fantasy_points_ppr": 141.0, "games_played": 17},
    {"player_display_name": "Jason Myers",        "position": "K", "recent_team": "SEA", "fantasy_points_ppr": 140.0, "games_played": 17},
    {"player_display_name": "Matt Gay",           "position": "K", "recent_team": "IND", "fantasy_points_ppr": 139.0, "games_played": 16},
    {"player_display_name": "Joshua Karty",       "position": "K", "recent_team": "LA", "fantasy_points_ppr": 135.0, "games_played": 17},
    {"player_display_name": "Will Reichard",      "position": "K", "recent_team": "MIN", "fantasy_points_ppr": 131.0, "games_played": 13},
    {"player_display_name": "Blake Grupe",        "position": "K", "recent_team": "NO",  "fantasy_points_ppr": 131.0, "games_played": 17},
    {"player_display_name": "Cam Little",         "position": "K", "recent_team": "JAX", "fantasy_points_ppr": 126.0, "games_played": 17},
    {"player_display_name": "Chad Ryland",        "position": "K", "recent_team": "ARI", "fantasy_points_ppr": 125.0, "games_played": 13},
    {"player_display_name": "Younghoe Koo",       "position": "K", "recent_team": "ATL", "fantasy_points_ppr": 120.0, "games_played": 14},
    {"player_display_name": "Joey Slye",          "position": "K", "recent_team": "NE",  "fantasy_points_ppr": 120.0, "games_played": 17},
    {"player_display_name": "Jake Moody",         "position": "K", "recent_team": "SF",  "fantasy_points_ppr": 118.0, "games_played": 14},
    {"player_display_name": "Austin Seibert",     "position": "K", "recent_team": "WAS", "fantasy_points_ppr": 115.0, "games_played": 9},
    {"player_display_name": "Cairo Santos",       "position": "K", "recent_team": "CHI", "fantasy_points_ppr": 109.0, "games_played": 17},
    {"player_display_name": "Nick Folk",          "position": "K", "recent_team": "TEN", "fantasy_points_ppr": 108.0, "games_played": 14},
    {"player_display_name": "Eddy Pineiro",       "position": "K", "recent_team": "CAR", "fantasy_points_ppr": 107.0, "games_played": 17},
    {"player_display_name": "Harrison Butker",    "position": "K", "recent_team": "KC",  "fantasy_points_ppr": 100.0, "games_played": 13},
    {"player_display_name": "Brandon McManus",    "position": "K", "recent_team": "GB",  "fantasy_points_ppr": 99.0,  "games_played": 11},
    {"player_display_name": "Evan McPherson",     "position": "K", "recent_team": "CIN", "fantasy_points_ppr": 94.0,  "games_played": 12},
    {"player_display_name": "Dustin Hopkins",     "position": "K", "recent_team": "CLE", "fantasy_points_ppr": 84.0,  "games_played": 16},
    {"player_display_name": "Greg Joseph",        "position": "K", "recent_team": "NYJ", "fantasy_points_ppr": 66.0,  "games_played": 8},
    {"player_display_name": "Anders Carlson",     "position": "K", "recent_team": "NYJ", "fantasy_points_ppr": 62.0,  "games_played": 7},
    {"player_display_name": "Brayden Narveson",   "position": "K", "recent_team": "TEN", "fantasy_points_ppr": 59.0,  "games_played": 7},
    {"player_display_name": "Matthew Wright",     "position": "K", "recent_team": "TEN", "fantasy_points_ppr": 56.0,  "games_played": 5},
    {"player_display_name": "Graham Gano",        "position": "K", "recent_team": "NYG", "fantasy_points_ppr": 50.0,  "games_played": 11},
    {"player_display_name": "Cade York",          "position": "K", "recent_team": "CIN", "fantasy_points_ppr": 46.0,  "games_played": 6},
    {"player_display_name": "Parker Romo",        "position": "K", "recent_team": "MIN", "fantasy_points_ppr": 46.0,  "games_played": 4},
    {"player_display_name": "Greg Zuerlein",      "position": "K", "recent_team": "NYJ", "fantasy_points_ppr": 41.0,  "games_played": 8},
    {"player_display_name": "Zane Gonzalez",      "position": "K", "recent_team": "WAS", "fantasy_points_ppr": 38.0,  "games_played": 6},
    {"player_display_name": "Matt Prater",        "position": "K", "recent_team": "ARI", "fantasy_points_ppr": 33.0,  "games_played": 4},
    {"player_display_name": "Riley Patterson",    "position": "K", "recent_team": "ATL", "fantasy_points_ppr": 30.0,  "games_played": 5},
    {"player_display_name": "Spencer Shrader",    "position": "K", "recent_team": "KC",  "fantasy_points_ppr": 26.0,  "games_played": 4},
    {"player_display_name": "Jack Browning",      "position": "K", "recent_team": "TB",  "fantasy_points_ppr": 0.0,   "games_played": 5},
])

In [28]:
# Combine offensive players with D/ST and K into one full player pool
final = pd.concat([final, dst_data, k_data], ignore_index=True)
final = final.sort_values('fantasy_points_ppr', ascending=False).reset_index(drop=True)
# Confirm all six positions are now present
print(final.shape)
final['position'].value_counts()

(503, 5)

WR     172
RB     105
TE      93
QB      58
K       43
DST     32
Name: position, dtype: int64

In [29]:
# Re-check team depth now that D/ST and K are included
team_position_counts = final.groupby(["recent_team", "position"]).size().unstack(fill_value=0)
team_position_counts[(team_position_counts == 0).any(axis=1)]
team_position_counts

position     DST  K  QB  RB  TE  WR
recent_team
ARI            1  2   2   4   3   4
ATL            1  2   2   2   2   4
BAL            1  1   2   3   3   5
BUF            1  1   2   3   3   5
CAR            1  1   2   3   2   6
CHI            1  1   2   3   2   4
CIN            1  2   1   3   5   5
CLE            1  1   3   4   3   6
DAL            1  1   3   3   3   6
DEN            1  1   1   3   3   6
DET            1  1   1   4   2   5
GB             1  1   2   3   3   6
HOU            1  1   2   4   2   6
IND            1  1   2   3   4   5
JAX            1  1   2   3   3   5
KC             1  2   1   4   3   5
LA             1  1   1   3   3   6
LAC            1  1   2   4   5   7
LV             1  1   3   4   3   5
MIA            1  1   2   4   3   5
MIN            1  2   2   2   3   5
NE             1  1   2   3   2   7
NO             1  1   3   4   3   7
NYG            1  1   2   3   3   4
NYJ            1  3   1   3   3   5
PHI            1  1   2   3   2   5
PIT            1  1   2   3   4   5
SEA            1  1   1   3   3   5
SF             1  1   1   4   2   5
TB             1  2   1   3   2   7
TEN            1  3   2   3   3   5
WAS            1  2   1   4   3   6

In [30]:
# Round fantasy point totals to 1 decimal place for cleaner display
final['fantasy_points_ppr'] = final['fantasy_points_ppr'].round(1)

In [31]:
# Export the final cleaned data 
final.to_csv("../backend/app/data/players_2024.csv", index=False)